package genconfig

const mobileConfigTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
 <key>PayloadContent</key>
 <array>
  <dict>
   <key>Password</key>
   <string>{{.PrivateKeyPassword}}</string>
   <key>PayloadCertificateFileName</key>
   <string>client.cert.p12</string>
   <key>PayloadContent</key>
   <data>
{{.PrivateKey}}
   </data>
   <key>PayloadDescription</key>
   <string>PKCS#12</string>
   <key>PayloadDisplayName</key>
   <string>client.cert.p12</string>
   <key>PayloadIdentifier</key>
   <string>com.apple.security.pkcs12.{{.UUID1}}</string>
   <key>PayloadType</key>
   <string>com.apple.security.pkcs12</string>
   <key>PayloadUUID</key>
   <string>{{.UUID1}}</string>
   <key>PayloadVersion</key>
   <integer>1</integer>
  </dict>
  <dict>
   <key>PayloadCertificateFileName</key>
   <string>ca.cer</string>
   <key>PayloadContent</key>
   <data>
{{.CACert}}
   </data>
   <key>PayloadDescription</key>
   <string>CA</string>
   <key>PayloadDisplayName</key>
   <string>strongSwan Root CA</string>
   <key>PayloadIdentifier</key>
   <string>com.apple.security.root.{{.UUID2}}</string>
   <key>PayloadType</key>
   <string>com.apple.security.root</string>
   <key>PayloadUUID</key>
   <string>{{.UUID2}}</string>
   <key>PayloadVersion</key>
   <integer>1</integer>
  </dict>
  <dict>
   <key>IKEv2</key>
   <dict>
    <key>OnDemandEnabled</key>
    <integer>1</integer>
    <key>OnDemandRules</key>
    <array>
    <dict>
    <key>Action</key>
    <string>Connect</string>
    </dict>
    </array>
    <key>AuthenticationMethod</key>
    <string>Certificate</string>
    <key>ChildSecurityAssociationParameters</key>
    <dict>
    <key>DiffieHellmanGroup</key>
        <integer>19</integer>
        <key>EncryptionAlgorithm</key>
        <string>AES-128-GCM</string>
        <key>IntegrityAlgorithm</key>
        <string>SHA2-512</string>
        <key>LifeTimeInMinutes</key>
        <integer>20</integer>
    </dict>
    <key>DeadPeerDetectionRate</key>
    <string>Medium</string>
    <key>DisableMOBIKE</key>
    <integer>0</integer>
    <key>DisableRedirect</key>
    <integer>1</integer>
    <key>EnableCertificateRevocationCheck</key>
    <integer>0</integer>
    <key>EnablePFS</key>
    <true/>
    <key>IKESecurityAssociationParameters</key>
    <dict>
        <key>DiffieHellmanGroup</key>
        <integer>19</integer>
        <key>EncryptionAlgorithm</key>
        <string>AES-128-GCM</string>
        <key>IntegrityAlgorithm</key>
        <string>SHA2-512</string>
        <key>LifeTimeInMinutes</key>
        <integer>20</integer>
    </dict>
    <key>LocalIdentifier</key>
    <string>{{.IP}}</string>
    <key>PayloadCertificateUUID</key>
    <string>{{.UUID1}}</string>
    <key>CertificateType</key>
    <string>ECDSA256</string>
    <key>ServerCertificateIssuerCommonName</key>
    <string>{{.IP}}</string>
    <key>RemoteAddress</key>
    <string>{{.IP}}</string>
    <key>RemoteIdentifier</key>
    <string>{{.IP}}</string>
    <key>UseConfigurationAttributeInternalIPSubnet</key>
    <integer>0</integer>
   </dict>
   <key>IPv4</key>
   <dict>
    <key>OverridePrimary</key>
    <integer>1</integer>
   </dict>
   <key>PayloadDescription</key>
   <string>Configures VPN settings</string>
   <key>PayloadDisplayName</key>
   <string>{{.Name}}</string>
   <key>PayloadIdentifier</key>
   <string>com.apple.vpn.managed.{{.UUID4}}</string>
   <key>PayloadType</key>
   <string>com.apple.vpn.managed</string>
   <key>PayloadUUID</key>
   <string>{{.UUID4}}</string>
   <key>PayloadVersion</key>
   <real>1</real>
   <key>Proxies</key>
   <dict>
    <key>HTTPEnable</key>
    <integer>0</integer>
    <key>HTTPSEnable</key>
    <integer>0</integer>
   </dict>
   <key>UserDefinedName</key>
   <string>{{.Name}}</string>
   <key>VPNType</key>
   <string>IKEv2</string>
  </dict>
  <dict>
   <key>PayloadCertificateFileName</key>
   <string>server.cer</string>
   <key>PayloadContent</key>
   <data>
{{.ServerCert}}
   </data>
   <key>PayloadDescription</key>
   <string>PKCS#1</string>
   <key>PayloadDisplayName</key>
   <string>{{.IP}}</string>
   <key>PayloadIdentifier</key>
   <string>com.apple.security.pkcs1.{{.UUID5}}</string>
   <key>PayloadType</key>
   <string>com.apple.security.pkcs1</string>
   <key>PayloadUUID</key>
   <string>{{.UUID5}}</string>
   <key>PayloadVersion</key>
   <integer>1</integer>
  </dict>
 </array>
 <key>PayloadDisplayName</key>
 <string>{{.Name}}</string>
 <key>PayloadIdentifier</key>
 <string>com.github.dan-v.dosxvpn.{{.Name}}</string>
 <key>PayloadRemovalDisallowed</key>
 <false/>
 <key>PayloadType</key>
 <string>Configuration</string>
 <key>PayloadUUID</key>
 <string>{{.UUID6}}</string>
 <key>PayloadVersion</key>
 <integer>1</integer>
</dict>
</plist>`
